-- CREATE SCHEMA IF NOT EXISTS `db_online_shopping` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `menu_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(45) NOT NULL,
  `price_per_item` DOUBLE NULL,
  `created_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
  )ENGINE=InnoDB DEFAULT CHARSET=UTF8;
